repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: (docs|\.phan|src\/templates|src\/UserInterface\/Components|data|scripts|server|public\/resources)
      - id: end-of-file-fixer
        exclude: (docs|tests|\.vscode|bin|scripts|\.gitignore)
      - id: check-json
        exclude: (.vscode)
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.11.1
    hooks:
    - id: commitizen
    - id: commitizen-branch
      stages:
      - pre-push
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-lint
        exclude: (tests\/DataProviders)
      - id: php-cs
        files: \.(php)$
        exclude: (tests|.phan|migrations|src\/config|public|phpstan\.php|tests\/unit\/DataProviders|src\/DI)
        args: ["--standard=PSR12", "--exclude=Squiz.Functions.MultiLineFunctionDeclaration,Squiz.WhiteSpace.ScopeClosingBrace", "-p"]
      - id: php-unit
      - id: php-stan
        files: \.(php)$
        exclude: (tests|src\/config|public|phpstan\.php|tests\/unit\/DataProviders)
