name: Build Check
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.php'
      - '.github/workflows/push.yml'
      - 'composer.lock'
      - 'phpunit*.xml'
jobs:
  os_build_check:
    uses: phpolar/github-workflows/.github/workflows/os-build-check.yml@v1
